### PR TITLE
validate value of records

### LINKED ISSUE #33: Defining a record with empty records deletes the record from PowerDNS remote but not from state file
This issue was reported [here](https://github.com/terraform-providers/terraform-provider-powerdns/issues/31#issuecomment-528086027).

# TL;DR:

* Version `1.1.0`:

| | `[]` | `[""]` | 
|---|---|---|
| Record removed from PowerDNS server | ✅  | ✅   |
| Resource removed from state file? | :x:  | ✅  | 
| Apply finished with success? | ✅ | :x: |

* [Proposed patch](https://github.com/terraform-providers/terraform-provider-powerdns/issues/31#issuecomment-528086027)

| | `[]` | `[""]` | 
|---|---|---|
| Record removed from PowerDNS server | ✅  | ✅   |
| Resource removed from state file? | ✅   | ✅  | 
| Apply finished with success? | :x: | :x: |

⚠️ Because we don't implement `Update`, it's important to note that in _all_ cases the record is recreated. So in cases where the record doesn't exist in the state file it's because it failed to create a new one (apply didn't finish with success).

# Long Version

Steps to reproduce:

## Environment with existing record

Environment:
```
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 24,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": []
}
$ cat test.tf
resource "powerdns_record" "foobar" {
  zone    = "sysa.xyz."
  name    = "something.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = ["127.0.0.1"]
}
$ terraform apply  -auto-approve
powerdns_record.foobar: Creating...
powerdns_record.foobar: Creation complete after 0s [id=something.sysa.xyz.:::A]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
{
  "offset": 0,
  "length": 19,
  "string": "something.sysa.xyz.",
  "captures": []
}
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 26,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "powerdns_record",
      "name": "foobar",
      "provider": "provider.powerdns",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "something.sysa.xyz.:::A",
            "name": "something.sysa.xyz.",
            "records": [
              "127.0.0.1"
            ],
            "set_ptr": null,
            "ttl": 300,
            "type": "A",
            "zone": "sysa.xyz."
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
$
```

### 1. Changing the value of `records` to `[]`:

```
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 48,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "powerdns_record",
      "name": "foobar",
      "provider": "provider.powerdns",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "something.sysa.xyz.:::A",
            "name": "something.sysa.xyz.",
            "records": [
              "127.0.0.1"
            ],
            "set_ptr": null,
            "ttl": 300,
            "type": "A",
            "zone": "sysa.xyz."
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
{
  "offset": 0,
  "length": 19,
  "string": "something.sysa.xyz.",
  "captures": []
}
$ cat test.tf
resource "powerdns_record" "foobar" {
  zone    = "sysa.xyz."
  name    = "something.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = []
}
$ terraform apply  -auto-approve
powerdns_record.foobar: Refreshing state... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destroying... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destruction complete after 0s
powerdns_record.foobar: Creating...
powerdns_record.foobar: Creation complete after 0s [id=something.sysa.xyz.:::A]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 51,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "powerdns_record",
      "name": "foobar",
      "provider": "provider.powerdns",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "something.sysa.xyz.:::A",
            "name": "something.sysa.xyz.",
            "records": null,
            "set_ptr": null,
            "ttl": 300,
            "type": "A",
            "zone": "sysa.xyz."
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
```

### 2. Changing the value of `records` to `[""]` (same conditions/environment as 1):

```
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 54,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "powerdns_record",
      "name": "foobar",
      "provider": "provider.powerdns",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "something.sysa.xyz.:::A",
            "name": "something.sysa.xyz.",
            "records": [
              "127.0.0.1"
            ],
            "set_ptr": null,
            "ttl": 300,
            "type": "A",
            "zone": "sysa.xyz."
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
{
  "offset": 0,
  "length": 19,
  "string": "something.sysa.xyz.",
  "captures": []
}
$ cat test.tf
resource "powerdns_record" "foobar" {
  zone    = "sysa.xyz."
  name    = "something.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = [""]
}
$ terraform apply  -auto-approve
powerdns_record.foobar: Refreshing state... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destroying... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destruction complete after 0s
powerdns_record.foobar: Creating...

Error: Failed to create PowerDNS Record: Error creating record set: something.sysa.xyz.:::A, reason: "Record something.sysa.xyz./A '': Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content ''"

  on test.tf line 1, in resource "powerdns_record" "foobar":
   1: resource "powerdns_record" "foobar" {


$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 56,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": []
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
$
```

If the suggestion from [here](https://github.com/terraform-providers/terraform-provider-powerdns/issues/31#issuecomment-528086027) is applied, the behavior is:

A. Using `records = []`

```
$ terraform apply  -auto-approve
powerdns_record.foobar: Refreshing state... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destroying... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destruction complete after 0s
powerdns_record.foobar: Creating...

Error: Couldn't fetch PowerDNS Record: Unknown record ID format

  on test.tf line 1, in resource "powerdns_record" "foobar":
   1: resource "powerdns_record" "foobar" {


$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 42,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": []
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
$
```

B. Using `records = [""]`:

```
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 44,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "powerdns_record",
      "name": "foobar",
      "provider": "provider.powerdns",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "something.sysa.xyz.:::A",
            "name": "something.sysa.xyz.",
            "records": [
              "127.0.0.1"
            ],
            "set_ptr": null,
            "ttl": 300,
            "type": "A",
            "zone": "sysa.xyz."
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
{
  "offset": 0,
  "length": 19,
  "string": "something.sysa.xyz.",
  "captures": []
}
$ cat test.tf
resource "powerdns_record" "foobar" {
  zone    = "sysa.xyz."
  name    = "something.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = [""]
}
$ terraform apply  -auto-approve
powerdns_record.foobar: Refreshing state... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destroying... [id=something.sysa.xyz.:::A]
powerdns_record.foobar: Destruction complete after 0s
powerdns_record.foobar: Creating...

Error: Failed to create PowerDNS Record: Error creating record set: something.sysa.xyz.:::A, reason: "Record something.sysa.xyz./A '': Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content ''"

  on test.tf line 1, in resource "powerdns_record" "foobar":
   1: resource "powerdns_record" "foobar" {


$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 46,
  "lineage": "5d15eb7d-2f44-4172-ac9d-494cb2534cd2",
  "outputs": {},
  "resources": []
}
$ curl -X GET -H "X-Api-Key: secret" http://localhost:8081/api/v1/servers/localhost/zones/sysa.xyz. -s  | jq '.rrsets[].name | match("something.sysa.xyz.")'
$
```

### PR DESCRIPTION
**Pull request by splashx**
Closes #33 

The apply looks like this:

```
$ cat test.tf
resource "powerdns_record" "foobar" {
  zone    = "sysa.xyz."
  name    = "something.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = ["127.0.0.1"]
}

resource "powerdns_record" "foobar1" {
  zone    = "sysa.xyz."
  name    = "something1.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = []
}

resource "powerdns_record" "foobar2" {
  zone    = "sysa.xyz."
  name    = "something2.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = [""]
}

resource "powerdns_record" "foobar3" {
  zone    = "sysa.xyz."
  name    = "something3.sysa.xyz."
  type    = "A"
  ttl     = 300
  records = ["", "127.0.0.2"]
}

$ terraform init > /dev/null 2>&1
$ make build && \
cp $GOPATH/bin/terraform-provider-powerdns .terraform/plugins/darwin_amd64/terraform-provider-powerdns_v1.1.0_x4 && \
terraform init && \
terraform apply -auto-approve

==> Checking that code complies with gofmt requirements...
go install

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.powerdns: version = "~> 1.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
powerdns_record.foobar: Refreshing state... [id=something.sysa.xyz.:::A]
powerdns_record.foobar2: Creating...
powerdns_record.foobar3: Creating...
powerdns_record.foobar1: Creating...

Error: 'records' must not be empty

  on test.tf line 9, in resource "powerdns_record" "foobar1":
   9: resource "powerdns_record" "foobar1" {



Error: all values in 'records' must contain non-empty strings

  on test.tf line 17, in resource "powerdns_record" "foobar2":
  17: resource "powerdns_record" "foobar2" {



Error: all values in 'records' must contain non-empty strings

  on test.tf line 25, in resource "powerdns_record" "foobar3":
  25: resource "powerdns_record" "foobar3" {
```

### CODE REVIEW

**Comment by splashx** [comment]
Because `TXT` records can be empty, we can't really forbid it.

So the new push reflects that, and leaves to the PowerDNS API to handle the error. 

It's not pretty - but that's cleaner.

```
Error: 'records' must not be empty

  on test.tf line 9, in resource "powerdns_record" "foobar1":
   9: resource "powerdns_record" "foobar1" {



Error: Failed to create PowerDNS Record: Error creating record set: something2.sysa.xyz.:::A, reason: "Record something2.sysa.xyz./A '': Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content ''"

  on test.tf line 17, in resource "powerdns_record" "foobar2":
  17: resource "powerdns_record" "foobar2" {



Error: Failed to create PowerDNS Record: Error creating record set: something3.sysa.xyz.:::A, reason: "Record something3.sysa.xyz./A '': Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content ''"

  on test.tf line 25, in resource "powerdns_record" "foobar3":
  25: resource "powerdns_record" "foobar3" {

```

File: powerdns/resource_powerdns_record.go [hunk 1]
```diff
@@ -70,15 +70,37 @@ func resourcePDNSRecordCreate(d *schema.ResourceData, meta interface{}) error {
...
 	}
 
+	// begin: ValidateFunc
+	// https://www.terraform.io/docs/extend/schemas/schema-behaviors.html
+	// "ValidateFunc is not yet supported on lists or sets"
+	// when terraform will support ValidateFunc for non-primitives
+	// we can move this block there
+	for _, recs := range recs {
+		if len(strings.Trim(recs.(string), " ")) == 0 {
+			log.Printf("[WARN] One or more values in 'records' contain empty '' value(s)")
```
Comment (mbag) [inline powerdns/resource_powerdns_record.go]: @splashx  please create one more test for this branch, i.e. for record with an empty value in the list.

Comment (mbag) [reply powerdns/resource_powerdns_record.go]: After trying this out, there is no easy way to trigger this in an acceptance test. I'll merge this, but we should consider validation at `.tf` file level.
